---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: rhoas-quarkus-kafka-registry
  name: rhoas-quarkus-kafka-registry
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: rhoas-quarkus-kafka-registry
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: rhoas-quarkus-kafka-registry
  name: rhoas-quarkus-kafka-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rhoas-quarkus-kafka-registry
  
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rhoas-quarkus-kafka-registry
    
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/rhoas/rhoas-quarkus-kafka-registry-quickstart:latest
        imagePullPolicy: Always
        name: rhoas-quarkus-kafka-registry
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rhoas-quarkus-kafka-registry
  labels:
    app.kubernetes.io/name: rhoas-quarkus-kafka-registry
spec:
  to:
    kind: Service
    name: rhoas-quarkus-kafka-registry
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
